<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CommuneTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('communes')->insert([
            ['id' => 1, 'label' => 'Arica', 'tag' => 'arica', 'short' => 'Arica', 'province_id' => 1],
            ['id' => 2, 'label' => 'Camarones', 'tag' => 'camarones', 'short' => 'Camarones', 'province_id' => 1],
            ['id' => 3, 'label' => 'General Lagos', 'tag' => 'gral_lagos', 'short' => 'Gral. Lagos', 'province_id' => 2],
            ['id' => 4, 'label' => 'Putre', 'tag' => 'putre', 'short' => 'Putre', 'province_id' => 2],
            ['id' => 5, 'label' => 'Alto Hospicio', 'tag' => 'alto_hospicio', 'short' => 'A. Hospicio', 'province_id' => 3],
            ['id' => 6, 'label' => 'Iquique', 'tag' => 'iquique', 'short' => 'Iquique', 'province_id' => 3],
            ['id' => 7, 'label' => 'Camiña', 'tag' => 'camina', 'short' => 'Camiña', 'province_id' => 4],
            ['id' => 8, 'label' => 'Colchane', 'tag' => 'colchane', 'short' => 'Colchane', 'province_id' => 4],
            ['id' => 9, 'label' => 'Huara', 'tag' => 'huara', 'short' => 'Huara', 'province_id' => 4],
            ['id' => 10, 'label' => 'Pica', 'tag' => 'pica', 'short' => 'Pica', 'province_id' => 4],
            ['id' => 11, 'label' => 'Pozo Almonte', 'tag' => 'pozo_almonte', 'short' => 'P. Almonte', 'province_id' => 4],
            ['id' => 12, 'label' => 'Antofagasta', 'tag' => 'antofagasta', 'short' => 'Antofagasta', 'province_id' => 5],
            ['id' => 13, 'label' => 'Mejillones', 'tag' => 'mejillones', 'short' => 'Mejillones', 'province_id' => 5],
            ['id' => 14, 'label' => 'Sierra Gorda', 'tag' => 'sierra_gorda', 'short' => 'S. Gorda', 'province_id' => 5],
            ['id' => 15, 'label' => 'Taltal', 'tag' => 'taltal', 'short' => 'Taltal', 'province_id' => 5],
            ['id' => 16, 'label' => 'Calama', 'tag' => 'calama', 'short' => 'Calama', 'province_id' => 6],
            ['id' => 17, 'label' => 'Ollague', 'tag' => 'ollague', 'short' => 'Ollague', 'province_id' => 6],
            ['id' => 18, 'label' => 'San Pedro de Atacama', 'tag' => 'san_pedro_de_atacama', 'short' => 'San Pedro Atacama', 'province_id' => 6],
            ['id' => 19, 'label' => 'María Elena', 'tag' => 'maria_elena', 'short' => 'María Elena', 'province_id' => 7],
            ['id' => 20, 'label' => 'Tocopilla', 'tag' => 'tocopilla', 'short' => 'Tocopilla', 'province_id' => 7],
            ['id' => 21, 'label' => 'Chañaral', 'tag' => 'chanaral', 'short' => 'Chañaral', 'province_id' => 8],
            ['id' => 22, 'label' => 'Diego de Almagro', 'tag' => 'diego_de_almagro', 'short' => 'Diego de Almagro', 'province_id' => 8],
            ['id' => 23, 'label' => 'Caldera', 'tag' => 'caldera', 'short' => 'Caldera', 'province_id' => 9],
            ['id' => 24, 'label' => 'Copiapó', 'tag' => 'copiapo', 'short' => 'Copiapó', 'province_id' => 9],
            ['id' => 25, 'label' => 'Tierra Amarilla', 'tag' => 'tierra_amarilla', 'short' => 'Tierra Amarilla', 'province_id' => 9],
            ['id' => 26, 'label' => 'Alto del Carmen', 'tag' => 'alto_del_carmen', 'short' => 'A. del Carmen', 'province_id' => 10],
            ['id' => 27, 'label' => 'Freirina', 'tag' => 'freirina', 'short' => 'Freirina', 'province_id' => 10],
            ['id' => 28, 'label' => 'Huasco', 'tag' => 'huasco', 'short' => 'Huasco', 'province_id' => 10],
            ['id' => 29, 'label' => 'Vallenar', 'tag' => 'vallenar', 'short' => 'Vallenar', 'province_id' => 10],
            ['id' => 30, 'label' => 'Canela', 'tag' => 'canela', 'short' => 'Canela', 'province_id' => 11],
            ['id' => 31, 'label' => 'Illapel', 'tag' => 'illapel', 'short' => 'Illapel', 'province_id' => 11],
            ['id' => 32, 'label' => 'Los Vilos', 'tag' => 'los_vilos', 'short' => 'Los Vilos', 'province_id' => 11],
            ['id' => 33, 'label' => 'Salamanca', 'tag' => 'salamanca', 'short' => 'Salamanca', 'province_id' => 11],
            ['id' => 34, 'label' => 'Andacollo', 'tag' => 'andacollo', 'short' => 'Andacollo', 'province_id' => 12],
            ['id' => 35, 'label' => 'Coquimbo', 'tag' => 'coquimbo', 'short' => 'Coquimbo', 'province_id' => 12],
            ['id' => 36, 'label' => 'La Higuera', 'tag' => 'la_higuera', 'short' => 'La Higuera', 'province_id' => 12],
            ['id' => 37, 'label' => 'La Serena', 'tag' => 'la_serena', 'short' => 'La Serena', 'province_id' => 12],
            ['id' => 38, 'label' => 'Paihuano', 'tag' => 'paihuano', 'short' => 'Paihuano', 'province_id' => 12],
            ['id' => 39, 'label' => 'Vicuña', 'tag' => 'vicuna', 'short' => 'Vicuña', 'province_id' => 12],
            ['id' => 40, 'label' => 'Combarbalá', 'tag' => 'combarbala', 'short' => 'Combarbalá', 'province_id' => 13],
            ['id' => 41, 'label' => 'Monte Patria', 'tag' => 'monte_patria', 'short' => 'Monte Patria', 'province_id' => 13],
            ['id' => 42, 'label' => 'Ovalle', 'tag' => 'ovalle', 'short' => 'Ovalle', 'province_id' => 13],
            ['id' => 43, 'label' => 'Punitaqui', 'tag' => 'punitaqui', 'short' => 'Punitaqui', 'province_id' => 13],
            ['id' => 44, 'label' => 'Río Hurtado', 'tag' => 'rio_hurtado', 'short' => 'Río Hurtado', 'province_id' => 13],
            ['id' => 45, 'label' => 'Isla de Pascua', 'tag' => 'isla_de_pascua', 'short' => 'Isla de Pascua', 'province_id' => 14],
            ['id' => 46, 'label' => 'Calle Larga', 'tag' => 'calle_larga', 'short' => 'Calle Larga', 'province_id' => 15],
            ['id' => 47, 'label' => 'Los Andes', 'tag' => 'los_andes', 'short' => 'Los Andes', 'province_id' => 15],
            ['id' => 48, 'label' => 'Rinconada', 'tag' => 'rinconada', 'short' => 'Rinconada', 'province_id' => 15],
            ['id' => 49, 'label' => 'San Esteban', 'tag' => 'san_esteban', 'short' => 'San Esteban', 'province_id' => 15],
            ['id' => 50, 'label' => 'La Ligua', 'tag' => 'la_ligua', 'short' => 'La Ligua', 'province_id' => 16],
            ['id' => 51, 'label' => 'Papudo', 'tag' => 'papudo', 'short' => 'Papudo', 'province_id' => 16],
            ['id' => 52, 'label' => 'Petorca', 'tag' => 'petorca', 'short' => 'Petorca', 'province_id' => 16],
            ['id' => 53, 'label' => 'Zapallar', 'tag' => 'zapallar', 'short' => 'Zapallar', 'province_id' => 16],
            ['id' => 54, 'label' => 'Hijuelas', 'tag' => 'hijuelas', 'short' => 'Hijuelas', 'province_id' => 17],
            ['id' => 55, 'label' => 'La Calera', 'tag' => 'la_calera', 'short' => 'La Calera', 'province_id' => 17],
            ['id' => 56, 'label' => 'La Cruz', 'tag' => 'la_cruz', 'short' => 'La Cruz', 'province_id' => 17],
            ['id' => 57, 'label' => 'Limache', 'tag' => 'limache', 'short' => 'Limache', 'province_id' => 54],
            ['id' => 58, 'label' => 'Nogales', 'tag' => 'nogales', 'short' => 'Nogales', 'province_id' => 17],
            ['id' => 59, 'label' => 'Olmué', 'tag' => 'olmue', 'short' => 'Olmué', 'province_id' => 54],
            ['id' => 60, 'label' => 'Quillota', 'tag' => 'quillota', 'short' => 'Quillota', 'province_id' => 17],
            ['id' => 61, 'label' => 'Algarrobo', 'tag' => 'algarrobo', 'short' => 'Algarrobo', 'province_id' => 18],
            ['id' => 62, 'label' => 'Cartagena', 'tag' => 'cartagena', 'short' => 'Cartagena', 'province_id' => 18],
            ['id' => 63, 'label' => 'El Quisco', 'tag' => 'el_quisco', 'short' => 'El Quisco', 'province_id' => 18],
            ['id' => 64, 'label' => 'El Tabo', 'tag' => 'el_tabo', 'short' => 'El Tabo', 'province_id' => 18],
            ['id' => 65, 'label' => 'San Antonio', 'tag' => 'san_antonio', 'short' => 'San Antonio', 'province_id' => 18],
            ['id' => 66, 'label' => 'Santo Domingo', 'tag' => 'santo_domingo', 'short' => 'Sto. Domingo', 'province_id' => 18],
            ['id' => 67, 'label' => 'Catemu', 'tag' => 'catemu', 'short' => 'Catemu', 'province_id' => 19],
            ['id' => 68, 'label' => 'Llaillay', 'tag' => 'llaillay', 'short' => 'Llaillay', 'province_id' => 19],
            ['id' => 69, 'label' => 'Panquehue', 'tag' => 'panquehue', 'short' => 'Panquehue', 'province_id' => 19],
            ['id' => 70, 'label' => 'Putaendo', 'tag' => 'putaendo', 'short' => 'Putaendo', 'province_id' => 19],
            ['id' => 71, 'label' => 'San Felipe', 'tag' => 'san_felipe', 'short' => 'San Felipe', 'province_id' => 19],
            ['id' => 72, 'label' => 'Santa María', 'tag' => 'santa_maria', 'short' => 'Santa María', 'province_id' => 19],
            ['id' => 73, 'label' => 'Casablanca', 'tag' => 'casablanca', 'short' => 'Casablanca', 'province_id' => 20],
            ['id' => 74, 'label' => 'Concón', 'tag' => 'concon', 'short' => 'Concón', 'province_id' => 20],
            ['id' => 75, 'label' => 'Juan Fernández', 'tag' => 'juan_fernandez', 'short' => 'J. Fernández', 'province_id' => 20],
            ['id' => 76, 'label' => 'Puchuncaví', 'tag' => 'puchuncavi', 'short' => 'Puchuncaví', 'province_id' => 20],
            ['id' => 77, 'label' => 'Quilpué', 'tag' => 'quilpue', 'short' => 'Quilpué', 'province_id' => 54],
            ['id' => 78, 'label' => 'Quintero', 'tag' => 'quintero', 'short' => 'Quintero', 'province_id' => 20],
            ['id' => 79, 'label' => 'Valparaíso', 'tag' => 'valparaiso', 'short' => 'Valparaíso', 'province_id' => 20],
            ['id' => 80, 'label' => 'Villa Alemana', 'tag' => 'villa_alemana', 'short' => 'Villa Alemana', 'province_id' => 54],
            ['id' => 81, 'label' => 'Viña del Mar', 'tag' => 'vina_del_mar', 'short' => 'Viña del Mar', 'province_id' => 20],
            ['id' => 82, 'label' => 'Colina', 'tag' => 'colina', 'short' => 'Colina', 'province_id' => 21],
            ['id' => 83, 'label' => 'Lampa', 'tag' => 'lampa', 'short' => 'Lampa', 'province_id' => 21],
            ['id' => 84, 'label' => 'Tiltil', 'tag' => 'tiltil', 'short' => 'Tiltil', 'province_id' => 21],
            ['id' => 85, 'label' => 'Pirque', 'tag' => 'pirque', 'short' => 'Pirque', 'province_id' => 22],
            ['id' => 86, 'label' => 'Puente Alto', 'tag' => 'puente_alto', 'short' => 'Puente Alto', 'province_id' => 22],
            ['id' => 87, 'label' => 'San José de Maipo', 'tag' => 'san_jose_de_maipo', 'short' => 'San José de Maipo', 'province_id' => 22],
            ['id' => 88, 'label' => 'Buin', 'tag' => 'buin', 'short' => 'Buin', 'province_id' => 23],
            ['id' => 89, 'label' => 'Calera de Tango', 'tag' => 'calera_de_tango', 'short' => 'Calera de Tango', 'province_id' => 23],
            ['id' => 90, 'label' => 'Paine', 'tag' => 'paine', 'short' => 'Paine', 'province_id' => 23],
            ['id' => 91, 'label' => 'San Bernardo', 'tag' => 'san_bernardo', 'short' => 'San Bernardo', 'province_id' => 23],
            ['id' => 92, 'label' => 'Alhué', 'tag' => 'alhue', 'short' => 'Alhué', 'province_id' => 24],
            ['id' => 93, 'label' => 'Curacaví', 'tag' => 'curacavi', 'short' => 'Curacaví', 'province_id' => 24],
            ['id' => 94, 'label' => 'María Pinto', 'tag' => 'maria_pinto', 'short' => 'María Pinto', 'province_id' => 24],
            ['id' => 95, 'label' => 'Melipilla', 'tag' => 'melipilla', 'short' => 'Melipilla', 'province_id' => 24],
            ['id' => 96, 'label' => 'San Pedro', 'tag' => 'san_pedro', 'short' => 'San Pedro', 'province_id' => 24],
            ['id' => 97, 'label' => 'Cerrillos', 'tag' => 'cerrillos', 'short' => 'Cerrillos', 'province_id' => 25],
            ['id' => 98, 'label' => 'Cerro Navia', 'tag' => 'cerro_navia', 'short' => 'Cerro Navia', 'province_id' => 25],
            ['id' => 99, 'label' => 'Conchalí', 'tag' => 'conchali', 'short' => 'Conchalí', 'province_id' => 25],
            ['id' => 100, 'label' => 'El Bosque', 'tag' => 'el_bosque', 'short' => 'El Bosque', 'province_id' => 25]
        ]);

        \DB::table('communes')->insert([

            ['id' => 101, 'label' => 'Estación Central', 'tag' => 'estacion_central', 'short' => 'E. Central', 'province_id' => 25],
            ['id' => 102, 'label' => 'Huechuraba', 'tag' => 'huechuraba', 'short' => 'Huechuraba', 'province_id' => 25],
            ['id' => 103, 'label' => 'Independencia', 'tag' => 'independencia', 'short' => 'Independencia', 'province_id' => 25],
            ['id' => 104, 'label' => 'La Cisterna', 'tag' => 'la_cisterna', 'short' => 'La Cisterna', 'province_id' => 25],
            ['id' => 105, 'label' => 'La Granja', 'tag' => 'la_granja', 'short' => 'La Granja', 'province_id' => 25],
            ['id' => 106, 'label' => 'La Florida', 'tag' => 'la_florida', 'short' => 'La Florida', 'province_id' => 25],
            ['id' => 107, 'label' => 'La Pintana', 'tag' => 'la_pintana', 'short' => 'La Pintana', 'province_id' => 25],
            ['id' => 108, 'label' => 'La Reina', 'tag' => 'la_reina', 'short' => 'La Reina', 'province_id' => 25],
            ['id' => 109, 'label' => 'Las Condes', 'tag' => 'las_condes', 'short' => 'Las Condes', 'province_id' => 25],
            ['id' => 110, 'label' => 'Lo Barnechea', 'tag' => 'lo_barnechea', 'short' => 'Lo Barnechea', 'province_id' => 25],
            ['id' => 111, 'label' => 'Lo Espejo', 'tag' => 'lo_espejo', 'short' => 'Lo Espejo', 'province_id' => 25],
            ['id' => 112, 'label' => 'Lo Prado', 'tag' => 'lo_prado', 'short' => 'Lo Prado', 'province_id' => 25],
            ['id' => 113, 'label' => 'Macul', 'tag' => 'macul', 'short' => 'Macul', 'province_id' => 25],
            ['id' => 114, 'label' => 'Maipú', 'tag' => 'maipu', 'short' => 'Maipú', 'province_id' => 25],
            ['id' => 115, 'label' => 'Ñuñoa', 'tag' => 'nunoa', 'short' => 'Ñuñoa', 'province_id' => 25],
            ['id' => 116, 'label' => 'Pedro Aguirre Cerda', 'tag' => 'pedro_aguirre_cerda', 'short' => 'P. Aguirre Cerda', 'province_id' => 25],
            ['id' => 117, 'label' => 'Peñalolén', 'tag' => 'penalolen', 'short' => 'Peñalolén', 'province_id' => 25],
            ['id' => 118, 'label' => 'Providencia', 'tag' => 'providencia', 'short' => 'Providencia', 'province_id' => 25],
            ['id' => 119, 'label' => 'Pudahuel', 'tag' => 'pudahuel', 'short' => 'Pudahuel', 'province_id' => 25],
            ['id' => 120, 'label' => 'Quilicura', 'tag' => 'quilicura', 'short' => 'Quilicura', 'province_id' => 25],
            ['id' => 121, 'label' => 'Quinta Normal', 'tag' => 'quinta_normal', 'short' => 'Quinta Normal', 'province_id' => 25],
            ['id' => 122, 'label' => 'Recoleta', 'tag' => 'recoleta', 'short' => 'Recoleta', 'province_id' => 25],
            ['id' => 123, 'label' => 'Renca', 'tag' => 'renca', 'short' => 'Renca', 'province_id' => 25],
            ['id' => 124, 'label' => 'San Miguel', 'tag' => 'san_miguel', 'short' => 'San Miguel', 'province_id' => 25],
            ['id' => 125, 'label' => 'San Joaquín', 'tag' => 'san_joaquin', 'short' => 'San Joaquín', 'province_id' => 25],
            ['id' => 126, 'label' => 'San Ramón', 'tag' => 'san_ramon', 'short' => 'San Ramón', 'province_id' => 25],
            ['id' => 127, 'label' => 'Santiago', 'tag' => 'santiago', 'short' => 'Santiago', 'province_id' => 25],
            ['id' => 128, 'label' => 'Vitacura', 'tag' => 'vitacura', 'short' => 'Vitacura', 'province_id' => 25],
            ['id' => 129, 'label' => 'El Monte', 'tag' => 'el_monte', 'short' => 'El Monte', 'province_id' => 26],
            ['id' => 130, 'label' => 'Isla de Maipo', 'tag' => 'isla_de_maipo', 'short' => 'I. de Maipo', 'province_id' => 26],
            ['id' => 131, 'label' => 'Padre Hurtado', 'tag' => 'padre_hurtado', 'short' => 'Padre Hurtado', 'province_id' => 26],
            ['id' => 132, 'label' => 'Peñaflor', 'tag' => 'penaflor', 'short' => 'Peñaflor', 'province_id' => 26],
            ['id' => 133, 'label' => 'Talagante', 'tag' => 'talagante', 'short' => 'Talagante', 'province_id' => 26],
            ['id' => 134, 'label' => 'Codegua', 'tag' => 'codegua', 'short' => 'Codegua', 'province_id' => 27],
            ['id' => 135, 'label' => 'Coínco', 'tag' => 'coinco', 'short' => 'Coínco', 'province_id' => 27],
            ['id' => 136, 'label' => 'Coltauco', 'tag' => 'coltauco', 'short' => 'Coltauco', 'province_id' => 27],
            ['id' => 137, 'label' => 'Doñihue', 'tag' => 'donihue', 'short' => 'Doñihue', 'province_id' => 27],
            ['id' => 138, 'label' => 'Graneros', 'tag' => 'graneros', 'short' => 'Graneros', 'province_id' => 27],
            ['id' => 139, 'label' => 'Las Cabras', 'tag' => 'las_cabras', 'short' => 'Las Cabras', 'province_id' => 27],
            ['id' => 140, 'label' => 'Machalí', 'tag' => 'machali', 'short' => 'Machalí', 'province_id' => 27],
            ['id' => 141, 'label' => 'Malloa', 'tag' => 'malloa', 'short' => 'Malloa', 'province_id' => 27],
            ['id' => 142, 'label' => 'Mostazal', 'tag' => 'mostazal', 'short' => 'Mostazal', 'province_id' => 27],
            ['id' => 143, 'label' => 'Olivar', 'tag' => 'olivar', 'short' => 'Olivar', 'province_id' => 27],
            ['id' => 144, 'label' => 'Peumo', 'tag' => 'peumo', 'short' => 'Peumo', 'province_id' => 27],
            ['id' => 145, 'label' => 'Pichidegua', 'tag' => 'pichidegua', 'short' => 'Pichidegua', 'province_id' => 27],
            ['id' => 146, 'label' => 'Quinta de Tilcoco', 'tag' => 'quinta_de_tilcoco', 'short' => 'Qta. de Tilcoco', 'province_id' => 27],
            ['id' => 147, 'label' => 'Rancagua', 'tag' => 'rancagua', 'short' => 'Rancagua', 'province_id' => 27],
            ['id' => 148, 'label' => 'Rengo', 'tag' => 'rengo', 'short' => 'Rengo', 'province_id' => 27],
            ['id' => 149, 'label' => 'Requínoa', 'tag' => 'requinoa', 'short' => 'Requínoa', 'province_id' => 27],
            ['id' => 150, 'label' => 'San Vicente de Tagua Tagua', 'tag' => 'san_vicente_de_tagua_tagua', 'short' => 'San Vicente', 'province_id' => 27],
            ['id' => 151, 'label' => 'La Estrella', 'tag' => 'la_estrella', 'short' => 'La Estrella', 'province_id' => 28],
            ['id' => 152, 'label' => 'Litueche', 'tag' => 'litueche', 'short' => 'Litueche', 'province_id' => 28],
            ['id' => 153, 'label' => 'Marchihue', 'tag' => 'marchihue', 'short' => 'Marchihue', 'province_id' => 28],
            ['id' => 154, 'label' => 'Navidad', 'tag' => 'navidad', 'short' => 'Navidad', 'province_id' => 28],
            ['id' => 155, 'label' => 'Paredones', 'tag' => 'paredones', 'short' => 'Paredones', 'province_id' => 28],
            ['id' => 156, 'label' => 'Pichilemu', 'tag' => 'pichilemu', 'short' => 'Pichilemu', 'province_id' => 28],
            ['id' => 157, 'label' => 'Chépica', 'tag' => 'chepica', 'short' => 'Chépica', 'province_id' => 29],
            ['id' => 158, 'label' => 'Chimbarongo', 'tag' => 'chimbarongo', 'short' => 'Chimbarongo', 'province_id' => 29],
            ['id' => 159, 'label' => 'Lolol', 'tag' => 'lolol', 'short' => 'Lolol', 'province_id' => 29],
            ['id' => 160, 'label' => 'Nancagua', 'tag' => 'nancagua', 'short' => 'Nancagua', 'province_id' => 29],
            ['id' => 161, 'label' => 'Palmilla', 'tag' => 'palmilla', 'short' => 'Palmilla', 'province_id' => 29],
            ['id' => 162, 'label' => 'Peralillo', 'tag' => 'peralillo', 'short' => 'Peralillo', 'province_id' => 29],
            ['id' => 163, 'label' => 'Placilla', 'tag' => 'placilla', 'short' => 'Placilla', 'province_id' => 29],
            ['id' => 164, 'label' => 'Pumanque', 'tag' => 'pumanque', 'short' => 'Pumanque', 'province_id' => 29],
            ['id' => 165, 'label' => 'San Fernando', 'tag' => 'san_fernando', 'short' => 'San Fernando', 'province_id' => 29],
            ['id' => 166, 'label' => 'Santa Cruz', 'tag' => 'santa_cruz', 'short' => 'Santa Cruz', 'province_id' => 29],
            ['id' => 167, 'label' => 'Cauquenes', 'tag' => 'cauquenes', 'short' => 'Cauquenes', 'province_id' => 30],
            ['id' => 168, 'label' => 'Chanco', 'tag' => 'chanco', 'short' => 'Chanco', 'province_id' => 30],
            ['id' => 169, 'label' => 'Pelluhue', 'tag' => 'pelluhue', 'short' => 'Pelluhue', 'province_id' => 30],
            ['id' => 170, 'label' => 'Curicó', 'tag' => 'curico', 'short' => 'Curicó', 'province_id' => 31],
            ['id' => 171, 'label' => 'Hualañé', 'tag' => 'hualane', 'short' => 'Hualañé', 'province_id' => 31],
            ['id' => 172, 'label' => 'Licantén', 'tag' => 'licanten', 'short' => 'Licantén', 'province_id' => 31],
            ['id' => 173, 'label' => 'Molina', 'tag' => 'molina', 'short' => 'Molina', 'province_id' => 31],
            ['id' => 174, 'label' => 'Rauco', 'tag' => 'rauco', 'short' => 'Rauco', 'province_id' => 31],
            ['id' => 175, 'label' => 'Romeral', 'tag' => 'romeral', 'short' => 'Romeral', 'province_id' => 31],
            ['id' => 176, 'label' => 'Sagrada Familia', 'tag' => 'sagrada_familia', 'short' => 'Sagrada Familia', 'province_id' => 31],
            ['id' => 177, 'label' => 'Teno', 'tag' => 'teno', 'short' => 'Teno', 'province_id' => 31],
            ['id' => 178, 'label' => 'Vichuquén', 'tag' => 'vichuquen', 'short' => 'Vichuquén', 'province_id' => 31],
            ['id' => 179, 'label' => 'Colbún', 'tag' => 'colbun', 'short' => 'Colbún', 'province_id' => 32],
            ['id' => 180, 'label' => 'Linares', 'tag' => 'linares', 'short' => 'Linares', 'province_id' => 32],
            ['id' => 181, 'label' => 'Longaví', 'tag' => 'longavi', 'short' => 'Longaví', 'province_id' => 32],
            ['id' => 182, 'label' => 'Parral', 'tag' => 'parral', 'short' => 'Parral', 'province_id' => 32],
            ['id' => 183, 'label' => 'Retiro', 'tag' => 'retiro', 'short' => 'Retiro', 'province_id' => 32],
            ['id' => 184, 'label' => 'San Javier', 'tag' => 'san_javier', 'short' => 'San Javier', 'province_id' => 32],
            ['id' => 185, 'label' => 'Villa Alegre', 'tag' => 'villa_alegre', 'short' => 'Villa Alegre', 'province_id' => 32],
            ['id' => 186, 'label' => 'Yerbas Buenas', 'tag' => 'yerbas_buenas', 'short' => 'Yerbas Buenas', 'province_id' => 32],
            ['id' => 187, 'label' => 'Constitución', 'tag' => 'constitucion', 'short' => 'Constitución', 'province_id' => 33],
            ['id' => 188, 'label' => 'Curepto', 'tag' => 'curepto', 'short' => 'Curepto', 'province_id' => 33],
            ['id' => 189, 'label' => 'Empedrado', 'tag' => 'empedrado', 'short' => 'Empedrado', 'province_id' => 33],
            ['id' => 190, 'label' => 'Maule', 'tag' => 'maule', 'short' => 'Maule', 'province_id' => 33],
            ['id' => 191, 'label' => 'Pelarco', 'tag' => 'pelarco', 'short' => 'Pelarco', 'province_id' => 33],
            ['id' => 192, 'label' => 'Pencahue', 'tag' => 'pencahue', 'short' => 'Pencahue', 'province_id' => 33],
            ['id' => 193, 'label' => 'Río Claro', 'tag' => 'rio_claro', 'short' => 'Río Claro', 'province_id' => 33],
            ['id' => 194, 'label' => 'San Clemente', 'tag' => 'san_clemente', 'short' => 'San Clemente', 'province_id' => 33],
            ['id' => 195, 'label' => 'San Rafael', 'tag' => 'san_rafael', 'short' => 'San Rafael', 'province_id' => 33],
            ['id' => 196, 'label' => 'Talca', 'tag' => 'talca', 'short' => 'Talca', 'province_id' => 33],
            ['id' => 197, 'label' => 'Arauco', 'tag' => 'arauco', 'short' => 'Arauco', 'province_id' => 34],
            ['id' => 198, 'label' => 'Cañete', 'tag' => 'canete', 'short' => 'Cañete', 'province_id' => 34],
            ['id' => 199, 'label' => 'Contulmo', 'tag' => 'contulmo', 'short' => 'Contulmo', 'province_id' => 34],
            ['id' => 200, 'label' => 'Curanilahue', 'tag' => 'curanilahue', 'short' => 'Curanilahue', 'province_id' => 34]

        ]);

        \DB::table('communes')->insert([

            ['id' => 201, 'label' => 'Lebu', 'tag' => 'lebu', 'short' => 'Lebu', 'province_id' => 34],
            ['id' => 202, 'label' => 'Los Álamos', 'tag' => 'los_alamos', 'short' => 'Los Álamos', 'province_id' => 34],
            ['id' => 203, 'label' => 'Tirúa', 'tag' => 'tirua', 'short' => 'Tirúa', 'province_id' => 34],
            ['id' => 204, 'label' => 'Alto Biobío', 'tag' => 'alto_biobio', 'short' => 'Alto Biobío', 'province_id' => 35],
            ['id' => 205, 'label' => 'Antuco', 'tag' => 'antuco', 'short' => 'Antuco', 'province_id' => 35],
            ['id' => 206, 'label' => 'Cabrero', 'tag' => 'cabrero', 'short' => 'Cabrero', 'province_id' => 35],
            ['id' => 207, 'label' => 'Laja', 'tag' => 'laja', 'short' => 'Laja', 'province_id' => 35],
            ['id' => 208, 'label' => 'Los Ángeles', 'tag' => 'los_angeles', 'short' => 'Los Ángeles', 'province_id' => 35],
            ['id' => 209, 'label' => 'Mulchén', 'tag' => 'mulchen', 'short' => 'Mulchén', 'province_id' => 35],
            ['id' => 210, 'label' => 'Nacimiento', 'tag' => 'nacimiento', 'short' => 'Nacimiento', 'province_id' => 35],
            ['id' => 211, 'label' => 'Negrete', 'tag' => 'negrete', 'short' => 'Negrete', 'province_id' => 35],
            ['id' => 212, 'label' => 'Quilaco', 'tag' => 'quilaco', 'short' => 'Quilaco', 'province_id' => 35],
            ['id' => 213, 'label' => 'Quilleco', 'tag' => 'quilleco', 'short' => 'Quilleco', 'province_id' => 35],
            ['id' => 214, 'label' => 'San Rosendo', 'tag' => 'san_rosendo', 'short' => 'San Rosendo', 'province_id' => 35],
            ['id' => 215, 'label' => 'Santa Bárbara', 'tag' => 'santa_barbara', 'short' => 'Santa Bárbara', 'province_id' => 35],
            ['id' => 216, 'label' => 'Tucapel', 'tag' => 'tucapel', 'short' => 'Tucapel', 'province_id' => 35],
            ['id' => 217, 'label' => 'Yumbel', 'tag' => 'yumbel', 'short' => 'Yumbel', 'province_id' => 35],
            ['id' => 218, 'label' => 'Chiguayante', 'tag' => 'chiguayante', 'short' => 'Chiguayante', 'province_id' => 36],
            ['id' => 219, 'label' => 'Concepción', 'tag' => 'concepcion', 'short' => 'Concepción', 'province_id' => 36],
            ['id' => 220, 'label' => 'Coronel', 'tag' => 'coronel', 'short' => 'Coronel', 'province_id' => 36],
            ['id' => 221, 'label' => 'Florida', 'tag' => 'florida', 'short' => 'Florida', 'province_id' => 36],
            ['id' => 222, 'label' => 'Hualpén', 'tag' => 'hualpen', 'short' => 'Hualpén', 'province_id' => 36],
            ['id' => 223, 'label' => 'Hualqui', 'tag' => 'hualqui', 'short' => 'Hualqui', 'province_id' => 36],
            ['id' => 224, 'label' => 'Lota', 'tag' => 'lota', 'short' => 'Lota', 'province_id' => 36],
            ['id' => 225, 'label' => 'Penco', 'tag' => 'penco', 'short' => 'Penco', 'province_id' => 36],
            ['id' => 226, 'label' => 'San Pedro de La Paz', 'tag' => 'san_pedro_de_la_paz', 'short' => 'S. Pedro de La Paz', 'province_id' => 36],
            ['id' => 227, 'label' => 'Santa Juana', 'tag' => 'santa_juana', 'short' => 'Sta. Juana', 'province_id' => 36],
            ['id' => 228, 'label' => 'Talcahuano', 'tag' => 'talcahuano', 'short' => 'Talcahuano', 'province_id' => 36],
            ['id' => 229, 'label' => 'Tomé', 'tag' => 'tome', 'short' => 'Tomé', 'province_id' => 36],
            ['id' => 230, 'label' => 'Bulnes', 'tag' => 'bulnes', 'short' => 'Bulnes', 'province_id' => 55],
            ['id' => 231, 'label' => 'Chillán', 'tag' => 'chillan', 'short' => 'Chillán', 'province_id' => 55],
            ['id' => 232, 'label' => 'Chillán Viejo', 'tag' => 'chillan_viejo', 'short' => 'Chillán Viejo', 'province_id' => 55],
            ['id' => 233, 'label' => 'Cobquecura', 'tag' => 'cobquecura', 'short' => 'Cobquecura', 'province_id' => 37],
            ['id' => 234, 'label' => 'Coelemu', 'tag' => 'coelemu', 'short' => 'Coelemu', 'province_id' => 37],
            ['id' => 235, 'label' => 'Coihueco', 'tag' => 'coihueco', 'short' => 'Coihueco', 'province_id' => 56],
            ['id' => 236, 'label' => 'El Carmen', 'tag' => 'el_carmen', 'short' => 'El Carmen', 'province_id' => 55],
            ['id' => 237, 'label' => 'Ninhue', 'tag' => 'ninhue', 'short' => 'Ninhue', 'province_id' => 37],
            ['id' => 238, 'label' => 'Ñiquen', 'tag' => 'niquen', 'short' => 'Ñiquen', 'province_id' => 56],
            ['id' => 239, 'label' => 'Pemuco', 'tag' => 'pemuco', 'short' => 'Pemuco', 'province_id' => 55],
            ['id' => 240, 'label' => 'Pinto', 'tag' => 'pinto', 'short' => 'Pinto', 'province_id' => 55],
            ['id' => 241, 'label' => 'Portezuelo', 'tag' => 'portezuelo', 'short' => 'Portezuelo', 'province_id' => 37],
            ['id' => 242, 'label' => 'Quillón', 'tag' => 'quillon', 'short' => 'Quillón', 'province_id' => 55],
            ['id' => 243, 'label' => 'Quirihue', 'tag' => 'quirihue', 'short' => 'Quirihue', 'province_id' => 37],
            ['id' => 244, 'label' => 'Ránquil', 'tag' => 'ranquil', 'short' => 'Ránquil', 'province_id' => 37],
            ['id' => 245, 'label' => 'San Carlos', 'tag' => 'san_carlos', 'short' => 'San Carlos', 'province_id' => 56],
            ['id' => 246, 'label' => 'San Fabián', 'tag' => 'san_fabian', 'short' => 'San Fabián', 'province_id' => 56],
            ['id' => 247, 'label' => 'San Ignacio', 'tag' => 'san_ignacio', 'short' => 'San Ignacio', 'province_id' => 55],
            ['id' => 248, 'label' => 'San Nicolás', 'tag' => 'san_nicolas', 'short' => 'San Nicolás', 'province_id' => 56],
            ['id' => 249, 'label' => 'Treguaco', 'tag' => 'treguaco', 'short' => 'Treguaco', 'province_id' => 37],
            ['id' => 250, 'label' => 'Yungay', 'tag' => 'yungay', 'short' => 'Yungay', 'province_id' => 55],
            ['id' => 251, 'label' => 'Carahue', 'tag' => 'carahue', 'short' => 'Carahue', 'province_id' => 38],
            ['id' => 252, 'label' => 'Cholchol', 'tag' => 'cholchol', 'short' => 'Cholchol', 'province_id' => 38],
            ['id' => 253, 'label' => 'Cunco', 'tag' => 'cunco', 'short' => 'Cunco', 'province_id' => 38],
            ['id' => 254, 'label' => 'Curarrehue', 'tag' => 'curarrehue', 'short' => 'Curarrehue', 'province_id' => 38],
            ['id' => 255, 'label' => 'Freire', 'tag' => 'freire', 'short' => 'Freire', 'province_id' => 38],
            ['id' => 256, 'label' => 'Galvarino', 'tag' => 'galvarino', 'short' => 'Galvarino', 'province_id' => 38],
            ['id' => 257, 'label' => 'Gorbea', 'tag' => 'gorbea', 'short' => 'Gorbea', 'province_id' => 38],
            ['id' => 258, 'label' => 'Lautaro', 'tag' => 'lautaro', 'short' => 'Lautaro', 'province_id' => 38],
            ['id' => 259, 'label' => 'Loncoche', 'tag' => 'loncoche', 'short' => 'Loncoche', 'province_id' => 38],
            ['id' => 260, 'label' => 'Melipeuco', 'tag' => 'melipeuco', 'short' => 'Melipeuco', 'province_id' => 38],
            ['id' => 261, 'label' => 'Nueva Imperial', 'tag' => 'nueva_imperial', 'short' => 'Nva. Imperial', 'province_id' => 38],
            ['id' => 262, 'label' => 'Padre Las Casas', 'tag' => 'padre_las_casas', 'short' => 'P. Las Casas', 'province_id' => 38],
            ['id' => 263, 'label' => 'Perquenco', 'tag' => 'perquenco', 'short' => 'Perquenco', 'province_id' => 38],
            ['id' => 264, 'label' => 'Pitrufquén', 'tag' => 'pitrufquen', 'short' => 'Pitrufquén', 'province_id' => 38],
            ['id' => 265, 'label' => 'Pucón', 'tag' => 'pucon', 'short' => 'Pucón', 'province_id' => 38],
            ['id' => 266, 'label' => 'Puerto Saavedra', 'tag' => 'puerto_saavedra', 'short' => 'Pto. Saavedra', 'province_id' => 38],
            ['id' => 267, 'label' => 'Temuco', 'tag' => 'temuco', 'short' => 'Temuco', 'province_id' => 38],
            ['id' => 268, 'label' => 'Teodoro Schmidt', 'tag' => 'teodoro_schmidt', 'short' => 'Teodoro Schmidt', 'province_id' => 38],
            ['id' => 269, 'label' => 'Toltén', 'tag' => 'tolten', 'short' => 'Toltén', 'province_id' => 38],
            ['id' => 270, 'label' => 'Vilcún', 'tag' => 'vilcun', 'short' => 'Vilcún', 'province_id' => 38],
            ['id' => 271, 'label' => 'Villarrica', 'tag' => 'villarrica', 'short' => 'Villarrica', 'province_id' => 38],
            ['id' => 272, 'label' => 'Angol', 'tag' => 'angol', 'short' => 'Angol', 'province_id' => 39],
            ['id' => 273, 'label' => 'Collipulli', 'tag' => 'collipulli', 'short' => 'Collipulli', 'province_id' => 39],
            ['id' => 274, 'label' => 'Curacautín', 'tag' => 'curacautin', 'short' => 'Curacautín', 'province_id' => 39],
            ['id' => 275, 'label' => 'Ercilla', 'tag' => 'ercilla', 'short' => 'Ercilla', 'province_id' => 39],
            ['id' => 276, 'label' => 'Lonquimay', 'tag' => 'lonquimay', 'short' => 'Lonquimay', 'province_id' => 39],
            ['id' => 277, 'label' => 'Los Sauces', 'tag' => 'los_sauces', 'short' => 'Los Sauces', 'province_id' => 39],
            ['id' => 278, 'label' => 'Lumaco', 'tag' => 'lumaco', 'short' => 'Lumaco', 'province_id' => 39],
            ['id' => 279, 'label' => 'Purén', 'tag' => 'puren', 'short' => 'Purén', 'province_id' => 39],
            ['id' => 280, 'label' => 'Renaico', 'tag' => 'renaico', 'short' => 'Renaico', 'province_id' => 39],
            ['id' => 281, 'label' => 'Traiguén', 'tag' => 'traiguen', 'short' => 'Traiguén', 'province_id' => 39],
            ['id' => 282, 'label' => 'Victoria', 'tag' => 'victoria', 'short' => 'Victoria', 'province_id' => 39],
            ['id' => 283, 'label' => 'Corral', 'tag' => 'corral', 'short' => 'Corral', 'province_id' => 40],
            ['id' => 284, 'label' => 'Lanco', 'tag' => 'lanco', 'short' => 'Lanco', 'province_id' => 40],
            ['id' => 285, 'label' => 'Los Lagos', 'tag' => 'los_lagos', 'short' => 'Los Lagos', 'province_id' => 40],
            ['id' => 286, 'label' => 'Máfil', 'tag' => 'mafil', 'short' => 'Máfil', 'province_id' => 40],
            ['id' => 287, 'label' => 'Mariquina', 'tag' => 'mariquina', 'short' => 'Mariquina', 'province_id' => 40],
            ['id' => 288, 'label' => 'Paillaco', 'tag' => 'paillaco', 'short' => 'Paillaco', 'province_id' => 40],
            ['id' => 289, 'label' => 'Panguipulli', 'tag' => 'panguipulli', 'short' => 'Panguipulli', 'province_id' => 40],
            ['id' => 290, 'label' => 'Valdivia', 'tag' => 'valdivia', 'short' => 'Valdivia', 'province_id' => 40],
            ['id' => 291, 'label' => 'Futrono', 'tag' => 'futrono', 'short' => 'Futrono', 'province_id' => 41],
            ['id' => 292, 'label' => 'La Unión', 'tag' => 'la_union', 'short' => 'La Unión', 'province_id' => 41],
            ['id' => 293, 'label' => 'Lago Ranco', 'tag' => 'lago_ranco', 'short' => 'Lago Ranco', 'province_id' => 41],
            ['id' => 294, 'label' => 'Río Bueno', 'tag' => 'rio_bueno', 'short' => 'Río Bueno', 'province_id' => 41],
            ['id' => 295, 'label' => 'Ancud', 'tag' => 'ancud', 'short' => 'Ancud', 'province_id' => 42],
            ['id' => 296, 'label' => 'Castro', 'tag' => 'castro', 'short' => 'Castro', 'province_id' => 42],
            ['id' => 297, 'label' => 'Chonchi', 'tag' => 'chonchi', 'short' => 'Chonchi', 'province_id' => 42],
            ['id' => 298, 'label' => 'Curaco de Vélez', 'tag' => 'curaco_de_velez', 'short' => 'C. de Vélez', 'province_id' => 42],
            ['id' => 299, 'label' => 'Dalcahue', 'tag' => 'dalcahue', 'short' => 'Dalcahue', 'province_id' => 42],
            ['id' => 300, 'label' => 'Puqueldón', 'tag' => 'puqueldon', 'short' => 'Puqueldón', 'province_id' => 42],
            ['id' => 301, 'label' => 'Queilén', 'tag' => 'queilen', 'short' => 'Queilén', 'province_id' => 42],
            ['id' => 302, 'label' => 'Quemchi', 'tag' => 'quemchi', 'short' => 'Quemchi', 'province_id' => 42],
            ['id' => 303, 'label' => 'Quellón', 'tag' => 'quellon', 'short' => 'Quellón', 'province_id' => 42],
            ['id' => 304, 'label' => 'Quinchao', 'tag' => 'quinchao', 'short' => 'Quinchao', 'province_id' => 42],
            ['id' => 305, 'label' => 'Calbuco', 'tag' => 'calbuco', 'short' => 'Calbuco', 'province_id' => 43],
            ['id' => 306, 'label' => 'Cochamó', 'tag' => 'cochamo', 'short' => 'Cochamó', 'province_id' => 43],
            ['id' => 307, 'label' => 'Fresia', 'tag' => 'fresia', 'short' => 'Fresia', 'province_id' => 43],
            ['id' => 308, 'label' => 'Frutillar', 'tag' => 'frutillar', 'short' => 'Frutillar', 'province_id' => 43],
            ['id' => 309, 'label' => 'Llanquihue', 'tag' => 'llanquihue', 'short' => 'Llanquihue', 'province_id' => 43],
            ['id' => 310, 'label' => 'Los Muermos', 'tag' => 'los_muermos', 'short' => 'Los Muermos', 'province_id' => 43],
            ['id' => 311, 'label' => 'Maullín', 'tag' => 'maullin', 'short' => 'Maullín', 'province_id' => 43],
            ['id' => 312, 'label' => 'Puerto Montt', 'tag' => 'puerto_montt', 'short' => 'Pto. Montt', 'province_id' => 43],
            ['id' => 313, 'label' => 'Puerto Varas', 'tag' => 'puerto_varas', 'short' => 'Pto. Varas', 'province_id' => 43],
            ['id' => 314, 'label' => 'Osorno', 'tag' => 'osorno', 'short' => 'Osorno', 'province_id' => 44],
            ['id' => 315, 'label' => 'Puerto Octay', 'tag' => 'puerto_octay', 'short' => 'Pto. Octay', 'province_id' => 44],
            ['id' => 316, 'label' => 'Purranque', 'tag' => 'purranque', 'short' => 'Purranque', 'province_id' => 44],
            ['id' => 317, 'label' => 'Puyehue', 'tag' => 'puyehue', 'short' => 'Puyehue', 'province_id' => 44],
            ['id' => 318, 'label' => 'Río Negro', 'tag' => 'rio_negro', 'short' => 'Río Negro', 'province_id' => 44],
            ['id' => 319, 'label' => 'San Juan de la Costa', 'tag' => 'san_juan_de_la_costa', 'short' => 'San Juan de la Costa', 'province_id' => 44],
            ['id' => 320, 'label' => 'San Pablo', 'tag' => 'san_pablo', 'short' => 'San Pablo', 'province_id' => 44],
            ['id' => 321, 'label' => 'Chaitén', 'tag' => 'chaiten', 'short' => 'Chaitén', 'province_id' => 45],
            ['id' => 322, 'label' => 'Futaleufú', 'tag' => 'futaleufu', 'short' => 'Futaleufú', 'province_id' => 45],
            ['id' => 323, 'label' => 'Hualaihué', 'tag' => 'hualaihue', 'short' => 'Hualaihué', 'province_id' => 45],
            ['id' => 324, 'label' => 'Palena', 'tag' => 'palena', 'short' => 'Palena', 'province_id' => 45],
            ['id' => 325, 'label' => 'Aysén', 'tag' => 'aysen', 'short' => 'Aysén', 'province_id' => 46],
            ['id' => 326, 'label' => 'Cisnes', 'tag' => 'cisnes', 'short' => 'Cisnes', 'province_id' => 46],
            ['id' => 327, 'label' => 'Guaitecas', 'tag' => 'guaitecas', 'short' => 'Guaitecas', 'province_id' => 46],
            ['id' => 328, 'label' => 'Cochrane', 'tag' => 'cochrane', 'short' => 'Cochrane', 'province_id' => 47],
            ['id' => 329, 'label' => 'O\'higgins', 'tag' => 'ohiggins', 'short' => 'O\'higgins', 'province_id' => 47],
            ['id' => 330, 'label' => 'Tortel', 'tag' => 'tortel', 'short' => 'Tortel', 'province_id' => 47],
            ['id' => 331, 'label' => 'Coyhaique', 'tag' => 'coyhaique', 'short' => 'Coyhaique', 'province_id' => 48],
            ['id' => 332, 'label' => 'Lago Verde', 'tag' => 'lago_verde', 'short' => 'Lago Verde', 'province_id' => 48],
            ['id' => 333, 'label' => 'Chile Chico', 'tag' => 'chile_chico', 'short' => 'Chile Chico', 'province_id' => 49],
            ['id' => 334, 'label' => 'Río Ibáñez', 'tag' => 'rio_ibanez', 'short' => 'Río Ibáñez', 'province_id' => 49],
            ['id' => 335, 'label' => 'Antártica', 'tag' => 'antartica', 'short' => 'Antártica', 'province_id' => 50],
            ['id' => 336, 'label' => 'Cabo de Hornos', 'tag' => 'cabo_de_hornos', 'short' => 'C. de Hornos', 'province_id' => 50],
            ['id' => 337, 'label' => 'Laguna Blanca', 'tag' => 'laguna_blanca', 'short' => 'Laguna Blanca', 'province_id' => 51],
            ['id' => 338, 'label' => 'Punta Arenas', 'tag' => 'punta_arenas', 'short' => 'Punta Arenas', 'province_id' => 51],
            ['id' => 339, 'label' => 'Río Verde', 'tag' => 'rio_verde', 'short' => 'Río Verde', 'province_id' => 51],
            ['id' => 340, 'label' => 'San Gregorio', 'tag' => 'san_gregorio', 'short' => 'San Gregorio', 'province_id' => 51],
            ['id' => 341, 'label' => 'Porvenir', 'tag' => 'porvenir', 'short' => 'Porvenir', 'province_id' => 52],
            ['id' => 342, 'label' => 'Primavera', 'tag' => 'primavera', 'short' => 'Primavera', 'province_id' => 52],
            ['id' => 343, 'label' => 'Timaukel', 'tag' => 'timaukel', 'short' => 'Timaukel', 'province_id' => 52],
            ['id' => 344, 'label' => 'Natales', 'tag' => 'natales', 'short' => 'Natales', 'province_id' => 53],
            ['id' => 345, 'label' => 'Torres del Paine', 'tag' => 'torres_del_paine', 'short' => 'T. del Paine', 'province_id' => 53],
            ['id' => 346, 'label' => 'Cabildo', 'tag' => 'cabildo', 'short' => 'Cabildo', 'province_id' => 16]

        ]);
    }
}
